### ISSUE TITLE
I can see clearly now?

### ISSUE THREAD

**Issue by johan-rain** [drblue/fed21-git-workshop#6]
I can see clearly now?

_Originally posted by @drblue in https://github.com/drblue/fed21-git-workshop/pull/2#pullrequestreview-981649578_

the rain is gone
I can see all obstacles in my way
Gone are the dark clouds that had me blind
It's gonna be a bright (bright)
Bright (bright) sunshiny day
It's gonna be a bright (bright)
Bright (bright) sunshiny day

**Comment by drblue** [comment]
![Disco disco! Good good!](https://i.makeagif.com/media/6-23-2017/Sx-ujB.gif)
